### ISSUE TITLE
Cannot build docker image locally (maven.abimon.org 523)

### ISSUE THREAD

**Issue by morganlaneap** [UnderMybrella/EternalJukebox#108]
### Before
- [x] I have checked for similar issues already
- [x] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
Getting errors whilst trying to build the Docker image locally due to one of the required sites (maven.abimon.org) returning a 523.

### Console Logs
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not resolve org.abimon:Visi:34.
     Required by:
         project :
      > Could not resolve org.abimon:Visi:34.
         > Could not get resource 'https://maven.abimon.org/org/abimon/Visi/34/Visi-34.pom'.
            > Could not GET 'https://maven.abimon.org/org/abimon/Visi/34/Visi-34.pom'. Received status code 523 from server: Origin Unreachable
   > Could not resolve org.abimon:UnitsKeptSimple:2.
     Required by:
         project :
      > Could not resolve org.abimon:UnitsKeptSimple:2.
         > Could not get resource 'https://maven.abimon.org/org/abimon/UnitsKeptSimple/2/UnitsKeptSimple-2.pom'.
            > Could not GET 'https://maven.abimon.org/org/abimon/UnitsKeptSimple/2/UnitsKeptSimple-2.pom'. Received status code 523 from server: Origin Unreachable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
This seems to be happening every time I've tried.

### Song
N/A

**Comment by UnderMybrella** [comment]
Hi, this is an issue at the moment with my main maven server being down, however it has been deprecated - if you change `maven.abimon.org` to `maven.brella.dev`, things should work smoothly

**Comment by mnemocron** [comment]
If anyone else is having the same issue, you have to edit the following file/line:

```
./build.gradle:19:    maven { url 'https://maven.abimon.org' }
```

---
And I guess this relates to the original issue: I got a **403 Forbidden**

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not resolve org.abimon:Visi:34.
     Required by:
         project :
      > Could not resolve org.abimon:Visi:34.
         > Could not get resource 'https://maven.abimon.org/org/abimon/Visi/34/Visi-34.pom'.
            > Could not GET 'https://maven-cloud.abimon.org/org/abimon/Visi/34/Visi-34.pom'. Received status code 403 from server: Forbidden
   > Could not resolve org.abimon:UnitsKeptSimple:2.
     Required by:
         project :
      > Could not resolve org.abimon:UnitsKeptSimple:2.
         > Could not get resource 'https://maven.abimon.org/org/abimon/UnitsKeptSimple/2/UnitsKeptSimple-2.pom'.
            > Could not GET 'https://maven-cloud.abimon.org/org/abimon/UnitsKeptSimple/2/UnitsKeptSimple-2.pom'. Received status code 403 from server: Forbidden
```

**Comment by mnemocron** [comment]
And the same issue persists with the jar version as well, but there you cannot change it as easily without rebuilding the jar.

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
        at java.lang.reflect.Field.get(Field.java:393)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:114)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt)
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:239)
        at org.abimon.eternalJukebox.EternalJukebox.<clinit>(EternalJukebox.kt:217)
Caused by: java.lang.IllegalArgumentException: Cannot find property file: hikari.properties
        at com.zaxxer.hikari.HikariConfig.loadProperties(HikariConfig.java:1189)
        at com.zaxxer.hikari.HikariConfig.<init>(HikariConfig.java:148)
        at org.abimon.eternalJukebox.data.database.JDBCDatabase.<clinit>(JDBCDatabase.kt:14)
        ... 12 more
java.lang.NoClassDefFoundError: Could not initialize class org.abimon.eternalJukebox.EternalJukebox
```
