### ISSUE TITLE
Null value in baseDomain in eternaljukebox-master_main_1

### ISSUE THREAD

**Issue by Mosquitobrain** [UnderMybrella/EternalJukebox#111]
### Before
- [X] I have checked for similar issues already
- [X] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
When trying to run image I get null value in baseDomain and container immediately exits.

### Console Logs
Exception in thread "main" java.lang.ExceptionInInitializerError

Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.abimon.eternalJukebox.objects.JukeboxConfig] value failed for JSON property baseDomain due to missing (therefore NULL) value for creator parameter baseDomain which is a non-nullable type

at [Source: (File); line: 39, column: 35] (through reference chain: org.abimon.eternalJukebox.objects.JukeboxConfig["baseDomain"])
at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:53)
at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
at org.abimon.eternalJukebox.EternalJukebox.<clinit>(EternalJukebox.kt:122)
### Song
N/A

### Additional Information
This was a fresh build. I am very new to docker in general and I don't know if I was supposed to modify that value in a config file.
Windows 10

**Comment by Mosquitobrain** [comment]
I found the variable in the envvar_config.yaml but I don't know what to set it to.

**Comment by Mosquitobrain** [comment]
Fixed by setting domain to 127.0.0.1.
