### ISSUE TITLE
Can't load songs using own server setup

### ISSUE THREAD

**Issue by EvaisaGiac** [UnderMybrella/EternalJukebox#12]
Okay i might be really stupid or something but i am trying to run this from source after building it and i am getting this error in the console when trying to load a song.

`SEVERE: Unexpected exception in route
java.lang.IllegalStateException: context.bodyAsString must not be null
    at org.abimon.eternalJukebox.EternalJukeboxKt.shrink(EternalJukebox.kt:544)
    at org.abimon.eternalJukebox.EternalJukeboxKt$main$21$1.invoke(EternalJukebox.kt:313)
    at org.abimon.eternalJukebox.EternalJukeboxKt$main$21$1.invoke(EternalJukebox.kt)
    at org.abimon.eternalJukebox.EternalJukeboxKt$sam$Handler$29eb28fa.handle(EternalJukebox.kt)
    at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
    at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)`

along with all this
https://pastebin.com/Dd4ZFbc1

Is there any guide on how to set it up correctly?
Thanks <3

**Comment by UnderMybrella** [comment]
Not quite yet, it's planned soon, however that issue isn't actually your fault (probably, at least).

Basically, Spotify is complaining about the authentication token it's been passed. Make sure that you're providing a correct client ID + secret key, and try restarting. I had a similar error and just restarting fixed it. My error handling isn't great so far, although that's being worked on.

**Comment by EvaisaGiac** [comment]
Hmm pretty sure it's correct but could it be that i just have my files lying in the wrong folders? or that the config isn't put together correctly because the client id and key should be correct
The search works fine too but i don't know if that actually uses them

(I basically just threw all the files in different folders untill it worked xD and looked in the kt file to figure out what to put in the config because it wasn't in the default one the client id and stuff)

**Comment by UnderMybrella** [comment]
Yeah, sorry about the lack of documentation for everything, I wasn't really expecting anyone to try running their own server but here we are. I'll be sure to do what I can to put something together.

As for your config file and setup, would you mind copying your config into something like Pastebin/Hastebin, obviously copying out your secret key/anything else that's confidential, and I'll have a look? Similar thing with your folder layout.

**Comment by EvaisaGiac** [comment]
Well i mean i am always up for a challenge xD Running something without documentation is a good puzzle lol
Basically i just like looking through code how something works and running it on my own server

Anyway here is my config:
https://ghostbin.com/paste/g9mx6

And i put my files on github so you can see what a mess i made.. (be prepared lol)
https://github.com/EvaisaGiac/EternalJukebox

I don't know if you have time maybe but could you help me with the file structure?

**Comment by UnderMybrella** [comment]
Everything actually looks to be alright (unless I'm missing something relatively obvious). I brought this up before, but have you tried restarting? It's possible that the Spotify token has somehow gotten invalidated somewhere, and I don't pick up on it. Always worth a shot.

**Comment by EvaisaGiac** [comment]
Yeah i have, i also tried running on both windows and linux, i can try generating a new spotify key maybe

**Comment by UnderMybrella** [comment]
Hrm, that's really weird. Try that, see what happens? I'm not too sure, sorry

**Comment by EvaisaGiac** [comment]
This is all that comes up on windows now and it gets stuck on loading track
Do you know of a way i can check if it actually gets the valid token? then again i don't know if this particular error has to do with that

`Jun 03, 2017 4:45:22 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.IllegalStateException: context.bodyAsString must not be null
        at org.abimon.eternalJukebox.EternalJukeboxKt.shrink(EternalJukebox.kt:544)
        at org.abimon.eternalJukebox.EternalJukeboxKt$main$21$1.invoke(EternalJukebox.kt:313)
        at org.abimon.eternalJukebox.EternalJukeboxKt$main$21$1.invoke(EternalJukebox.kt)
        at org.abimon.eternalJukebox.EternalJukeboxKt$sam$Handler$29eb28fa.handle(EternalJukebox.kt)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`

**Comment by EvaisaGiac** [comment]
shot in the dark but maybe it didn't build correctly or something? i don't know anymore

**Comment by EvaisaGiac** [comment]
how did i somehow close it

**Comment by EvaisaGiac** [comment]
shot in the dark but maybe it didn't build correctly or something? i don't know anymore

**Comment by UnderMybrella** [comment]
Don't know, but I do know why that error is happening at least. If you add a "uploads" key to your config file and set it to true, that error at least should go away. Might fix the other one too?

**Comment by EvaisaGiac** [comment]
Okay yeah that worked for that one but still got this spotify error

`type=jukebox&id=05KfyCEE6otdlT1pp2VIjP
Jun 03, 2017 4:54:52 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.abimon.eternalJukebox.objects.SpotifyTrack] value failed for JSON property href due to missing (therefore NULL) value for creator parameter href which is a non-nullable type
 at [Source: {
  "error": {
    "status": 400,
    "message": "Only valid bearer authentication supported"
  }
}; line: 6, column: 1] (through reference chain: org.abimon.eternalJukebox.objects.SpotifyTrack["href"])
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
        at com.mashape.unirest.request.BaseRequest.asObject(BaseRequest.java:80)
        at org.abimon.eternalJukebox.EternalJukeboxKt.songForID(EternalJukebox.kt:622)
        at org.abimon.eternalJukebox.EternalJukeboxKt.song(EternalJukebox.kt:607)
        at org.abimon.eternalJukebox.EternalJukeboxKt$main$13$1.invoke(EternalJukebox.kt:286)
        at org.abimon.eternalJukebox.EternalJukeboxKt$main$13$1.invoke(EternalJukebox.kt)
        at org.abimon.eternalJukebox.EternalJukeboxKt$sam$Handler$29eb28fa.handle(EternalJukebox.kt)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.abimon.eternalJukebox.objects.SpotifyTrack] value failed for JSON property href due to missing (therefore NULL) value for creator parameter href which is a non-nullable type
 at [Source: {
  "error": {
    "status": 400,
    "message": "Only valid bearer authentication supported"
  }
}; line: 6, column: 1] (through reference chain: org.abimon.eternalJukebox.objects.SpotifyTrack["href"])
        at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
        ... 12 more
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.abimon.eternalJukebox.objects.SpotifyTrack] value failed for JSON property href due to missing (therefore NULL) value for creator parameter href which is a non-nullable type
 at [Source: {
  "error": {
    "status": 400,
    "message": "Only valid bearer authentication supported"
  }
}; line: 6, column: 1] (through reference chain: org.abimon.eternalJukebox.objects.SpotifyTrack["href"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:44)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
        at org.abimon.eternalJukebox.EternalJukeboxKt$main$1.readValue(EternalJukebox.kt:132)
        at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:101)
        ... 13 more`

**Comment by EvaisaGiac** [comment]
Yeah it fixed that error thanks, now the spotify one only remains which just confuses my at this point because i also regenerated the key so it really can't be that

https://ghostbin.com/paste/nks8y

**Comment by EvaisaGiac** [comment]
I don't miss anything else in the config?

**Comment by UnderMybrella** [comment]
You certainly shouldn't be, that's really bizarre. 

If you can wait a day or so, I'll push something that should help out in that regard? Until then, I'm not sure what else can be done

**Comment by EvaisaGiac** [comment]
Alright, thanks anyway

**Comment by EvaisaGiac** [comment]
Okay i am still messing around with it trying to get something to work and after rebuilding it on windows it doesn't give that error anymore, however it still gets stuck on loading track but the only errors i get are in the chrome console and not in the terminal
http://imgur.com/a/ekpfV

I'm sorry i should probably stop worrying about it for now

**Comment by UnderMybrella** [comment]
Could you try downloading a prebuilt jar from [here](http://130.211.36.145/built.jar)? Run that with your config file and the other files and see what you get.

**Comment by EvaisaGiac** [comment]
Hmm can you tell me what files i put with it and stuff where? i kind of want to figure out this mess of folders

**Comment by UnderMybrella** [comment]
Your setup should look just like this repo has the files:
* Your Directory
  * jukebox_index.html
  * jukebox_go.html
  * ...
  * config.json
  * EternalJukebox.jar
  * files
    * jremix.js
    * ...

**Comment by EvaisaGiac** [comment]
How am i supposed to run it? I didn't have that jar in my previous setup at all, if i try to run it from a bat file or console i get this error

`Exception in thread "main" java.lang.IllegalArgumentException: Path must start with /
        at io.vertx.ext.web.impl.RouteImpl.checkPath(RouteImpl.java:402)
        at io.vertx.ext.web.impl.RouteImpl.<init>(RouteImpl.java:67)
        at io.vertx.ext.web.impl.RouterImpl.route(RouterImpl.java:89)
        at io.vertx.ext.web.impl.RouterImpl.get(RouterImpl.java:114)
        at org.abimon.eternalJukebox.API$setup$20.accept(API.kt:661)
        at org.abimon.eternalJukebox.API$setup$20.accept(API.kt:40)
        at java.util.HashMap.forEach(Unknown Source)
        at org.abimon.eternalJukebox.API.setup(API.kt:661)
        at org.abimon.eternalJukebox.EternalJukeboxKt.main(EternalJukebox.kt:182)`

**Comment by EvaisaGiac** [comment]
The original bat doesn't run it at all

**Comment by UnderMybrella** [comment]
What bat file are you using? To run it you'd want to execute `java -jar EternalJukebox.jar` in a console in the home directory.

As for that error, mistake on my part, try downloading the update [here](https://eternal.abimon.org/built.jar)

**Comment by EvaisaGiac** [comment]
yeah i did exactly that lol

**Comment by UnderMybrella** [comment]
And no luck, even with the update?

**Comment by EvaisaGiac** [comment]
no i didn't try yet sorry, give me a minute

**Comment by UnderMybrella** [comment]
Alright, take your time, it's cool!

**Comment by EvaisaGiac** [comment]
http://imgur.com/a/ZBSXx

It runs now but basically the same problem, first track i tried i got the same as last time (no error in the console)
And second one i think was also the same but gave a different result and also no console error

**Comment by UnderMybrella** [comment]
Right, sorry the other thing you'll need to do is update your files (like jukebox_go.html, jukebox_index.html) to the most recent ones, since the endpoints moved. Sorry

**Comment by EvaisaGiac** [comment]
I got the files off the git just now though? not using old ones

**Comment by UnderMybrella** [comment]
That's really weird, if you got the most recent ones you shouldn't be getting those 404s, that's really weird.

Could you open your local `jukebox_go.html` and search for "api/id"? If it's the old file it should pop up, but the new one won't have it

**Comment by EvaisaGiac** [comment]
can't find anything

**Comment by EvaisaGiac** [comment]
The google console error gets a little different with every different songs aswell it seems.. ehh

**Comment by UnderMybrella** [comment]
Could you send the errors through? One of the things I tried to do was to differentiate between errors for debugging

**Comment by EvaisaGiac** [comment]
i edited my last message ^ there are no errors at all in the cmd console only in chrome

**Comment by EvaisaGiac** [comment]
Atleast i am guessing this is supposed to popup in the console because it is all that pops up
`type=jukebox&id=05KfyCEE6otdlT1pp2VIjP
type=jukebox&id=1lgN0A2Vki2FTON5PYq42m`

**Comment by EvaisaGiac** [comment]
It doesnt load favourites anymore either 

> GET http://localhost:11037/api/popular_jukebox?count=12 404 (Not Found)

**Comment by EvaisaGiac** [comment]
i'm sorry i feel like i am breaking everything aahh

**Comment by UnderMybrella** [comment]
That console output is unintended but not unusual, I do need to take that out.

Do you have youtube-dl installed? If not, that would explain the 404 on `/api/songs`

That's quite possibly the `jukebox_go` file being cached? It's the old endpoint again

**Comment by EvaisaGiac** [comment]
let me remove cache

**Comment by EvaisaGiac** [comment]
i forgot that

**Comment by EvaisaGiac** [comment]
Where do i get youtube-dl from?

**Comment by UnderMybrella** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#installation

**Comment by EvaisaGiac** [comment]
I installed it now but still get the same error, some extra stuff does pop up in the console though
`type=jukebox&id=05KfyCEE6otdlT1pp2VIjP
[Default Song For ID] Non 200 code for song for 05KfyCEE6otdlT1pp2VIjP; iteration 0
[Default Song For ID] Non 200 code for song for 05KfyCEE6otdlT1pp2VIjP; iteration 1
[Default Song For ID] Non 200 code for song for 05KfyCEE6otdlT1pp2VIjP; iteration 2`

**Comment by EvaisaGiac** [comment]
http://imgur.com/a/Gkxgw

**Comment by UnderMybrella** [comment]
Non 200 is something, and it looks like I wasn't smart enough to put more debugging info there.
Considering the song ID is valid, it sounds like Spotify may be erroring again; if you request a different song does the same thing happen? In particular, does it get to the point of loading the song endpoint?

**Comment by EvaisaGiac** [comment]
Some songs get no console output and nothing in the chrome console either at all and get stuck on loading tracks.
Some have the loading tracks text disappear completely and give that last thing in the console plus the error in the chrome console or only a error in the chrome console and nothing in the normal one
And two songs i have tried completely crashed it and the website just went down

**Comment by EvaisaGiac** [comment]
It probably all has the same cause but the effects are slightly different per song it seems which is weird

**Comment by EvaisaGiac** [comment]
I can give you a link to it if you want to see for yourself
Also one beetles song in particular made it semi crash and now gives me this cool error in the search page
http://imgur.com/a/9hfLo

**Comment by UnderMybrella** [comment]
What two songs completely crashed it? That shouldn't happen so I'm curious about that. And that's really odd that it's different per song

**Comment by EvaisaGiac** [comment]
Do you have skype or discord? might be a little easier

**Comment by UnderMybrella** [comment]
Yep, if you wanted to jump in the Eternal Jukebox Discord there's a link [here](https://discord.gg/KWN5BfD), or if you just wanted to add me I'm UnderMybrella#4076

**Comment by EvaisaGiac** [comment]
you blocked friend requests ^

**Comment by EvaisaGiac** [comment]
i joined the discord
