### ISSUE TITLE
Unable to load song 

### ISSUE THREAD

**Issue by Akotowicz** [UnderMybrella/EternalJukebox#151]
### Before
- [ ] I have checked for similar issues already
- [ yes] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
[Description of the issue]
when i search for the song there appears to be one under name "Talking to the moon - Tiktok remix by Sick Kick Oh", but after clicking it there is none, as if it couldn't find it, black screen if you call it

### Console Logs
Error handling response: TypeError: p.logError is not a function
    at l.parseCss (chrome-extension://obhacaboehinamiaoafpljgofoapchgf/helpers/vendors/extended-css.js:4:6568)
    at Object.parseCss (chrome-extension://obhacaboehinamiaoafpljgofoapchgf/helpers/vendors/extended-css.js:4:7395)
    at new se (chrome-extension://obhacaboehinamiaoafpljgofoapchgf/helpers/vendors/extended-css.js:14:2187)
    at m (chrome-extension://obhacaboehinamiaoafpljgofoapchgf/helpers/content/preload.js:1:2488)
    at l (chrome-extension://obhacaboehinamiaoafpljgofoapchgf/helpers/content/preload.js:1:2220)
    at c (chrome-extension://obhacaboehinamiaoafpljgofoapchgf/helpers/content/preload.js:1:1933)
/api/site/shrink:1 Failed to load resource: the server responded with a status of 404 ()
jukebox_go.html?id=4WPshhoJzkap1MdmQQHA8Y:1394 Error: 
/api/audio/jukebox/4WPshhoJzkap1MdmQQHA8Y/location:1 Failed to load resource: the server responded with a status of 500 ()
/api/audio/jukebox/4WPshhoJzkap1MdmQQHA8Y:1 Failed to load resource: the server responded with a status of 500 ()
jremix.js?version=1-1-1:2 audio error DOMException: Unable to decode audio data
jukebox_go.html:1 Uncaught (in promise) DOMException: Unable to decode audio data

### Song
Title:
Talking to the moon - Tiktok remix by Sick Kick Oh
Link:
https://eternalbox.dev/jukebox_go.html?id=4WPshhoJzkap1MdmQQHA8Y

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by derekrebuck** [comment]
Has anyone provided you with a solution yet? I am experiencing the same issue.

**Comment by Akotowicz** [comment]
No one helped me yet, sorry
